---
- name: Deploy web and database servers
  hosts: all
  become: true
  vars:
    timezone: America/New_York
    ntp_server: pool.ntp.org
    http_proxy: http://proxy.example.com:8080
    https_proxy: http://proxy.example.com:8080
  roles:
    - role: common
    - role: web-servers
    - role: db-servers
    - role: load-balancers
